// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountContacts(ctx context.Context) (int64, error)
	CountContactsByStatus(ctx context.Context, status sql.NullString) (int64, error)
	CreateAnalyticsEvent(ctx context.Context, arg CreateAnalyticsEventParams) (AnalyticsEvent, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateExperience(ctx context.Context, arg CreateExperienceParams) (Experience, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateTechnology(ctx context.Context, arg CreateTechnologyParams) (Technology, error)
	DeleteContact(ctx context.Context, id string) error
	DeleteExperience(ctx context.Context, id string) error
	DeleteOldAnalyticsEvents(ctx context.Context) error
	DeleteService(ctx context.Context, id string) error
	DeleteTechnology(ctx context.Context, id string) error
	GetAnalyticsEvent(ctx context.Context, id string) (AnalyticsEvent, error)
	GetContact(ctx context.Context, id string) (Contact, error)
	GetContactByEmail(ctx context.Context, email string) (Contact, error)
	GetCurrentExperience(ctx context.Context) (Experience, error)
	GetEventCountsByType(ctx context.Context) ([]GetEventCountsByTypeRow, error)
	GetExperience(ctx context.Context, id string) (Experience, error)
	GetPageViewStats(ctx context.Context) ([]GetPageViewStatsRow, error)
	GetService(ctx context.Context, id string) (Service, error)
	GetTechnology(ctx context.Context, id string) (Technology, error)
	GetTechnologyByName(ctx context.Context, name string) (Technology, error)
	ListAnalyticsEvents(ctx context.Context, arg ListAnalyticsEventsParams) ([]AnalyticsEvent, error)
	ListAnalyticsEventsByType(ctx context.Context, arg ListAnalyticsEventsByTypeParams) ([]AnalyticsEvent, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	ListContactsByStatus(ctx context.Context, arg ListContactsByStatusParams) ([]Contact, error)
	// Experience queries
	ListExperiences(ctx context.Context) ([]Experience, error)
	// Services queries
	ListServices(ctx context.Context) ([]Service, error)
	// Technologies queries
	ListTechnologies(ctx context.Context) ([]Technology, error)
	ListTechnologiesByCategory(ctx context.Context, category string) ([]Technology, error)
	ListTechnologiesByLevel(ctx context.Context, proficiencyLevel string) ([]Technology, error)
	UpdateContactStatus(ctx context.Context, arg UpdateContactStatusParams) (Contact, error)
	UpdateExperience(ctx context.Context, arg UpdateExperienceParams) (Experience, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateTechnology(ctx context.Context, arg UpdateTechnologyParams) (Technology, error)
}

var _ Querier = (*Queries)(nil)
