# Cloud Build configuration for Holger Hahn Website
# Builds and deploys to Google Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/holger-hahn-website:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/holger-hahn-website:latest',
      '.'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/holger-hahn-website:$COMMIT_SHA'
    ]

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/holger-hahn-website:latest'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'holger-hahn-website',
      '--image', 'gcr.io/$PROJECT_ID/holger-hahn-website:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--cpu', '1',
      '--concurrency', '100',
      '--max-instances', '10',
      '--min-instances', '0',
      '--port', '8080',
      '--timeout', '300',
      '--set-env-vars', 'ENVIRONMENT=production,GIN_MODE=release'
    ]

# Store build artifacts
images:
  - 'gcr.io/$PROJECT_ID/holger-hahn-website:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/holger-hahn-website:latest'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_STANDARD_2'

# Build timeout (10 minutes)
timeout: '600s'

# Tags for filtering builds
tags:
  - 'holger-hahn-website'
  - 'cloud-run'
  - 'production'